<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOd8t7qc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOd8t7qc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOd8t7qc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOd8t7qc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOd8t7qc\App_KernelDevDebugContainer([
    'container.build_hash' => 'Od8t7qc',
    'container.build_id' => '0a1b455c',
    'container.build_time' => 1694763164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOd8t7qc');
