<?php

namespace ContainerOd8t7qc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtudiantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.go01M3X.App\Entity\Etudiant' shared service.
     *
     * @return \App\Entity\Etudiant
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.go01M3X": it needs an instance of "App\\Entity\\Etudiant" but this type has been excluded in "config/services.yaml".');
    }
}
