<?php

namespace ContainerOd8t7qc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHelloWordControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\HelloWordController' shared autowired service.
     *
     * @return \App\Controller\HelloWordController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/HelloWordController.php';

        $container->services['App\\Controller\\HelloWordController'] = $instance = new \App\Controller\HelloWordController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\HelloWordController', $container));

        return $instance;
    }
}
